_target_:  ex_4.vae.BetaVAE
latent_dim: 4
beta: 2
encoder:
  _target_: ex_4.model.EncoderResNetVAE
  latent_dim: ${..latent_dim}
  extra_layer: true
decoder:
  _target_: ex_4.model.DecoderResNetVAE
  channel_out: 3
  latent_dim: ${..latent_dim}
  extra_layer: true