name: celeba
max_epochs: 30
lr: 1e-4

train_loader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  batch_size: 64
  shuffle: true
  num_workers: 4

val_loader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  batch_size: 64
  shuffle: false
  num_workers: 4

defaults:
  - _self_
  - optional dataset: celeba
  - optional arch: vae
  - model: ${arch}_${dataset}
